# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ 
      ../cpu/no-spectre-meltdown-protection.nix
      ../gpu/nvidia-only.nix
      ../storage/partitionning/boot-root-swap-labeled.nix
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];

  boot.kernelModules = [ "kvm-intel" ];

  nix.maxJobs = lib.mkDefault 10;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
