# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    ../../hardware/cpu/no-spectre-meltdown-protection.nix
    ../../hardware/storage/partitionning/boot-root-swap-labeled.nix
    ../../hardware/gpu/intel-only.nix
];

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_acpi" ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
}
