# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/hardware/network/broadcom-43xx.nix>
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
      <nixos-hardware/common/cpu/intel/kaby-lake>
      <nixos-hardware/common/pc/laptop>
      <nixos-hardware/common/pc/laptop/acpi_call.nix>
    ];

 boot.kernelParams = [ "i915.fastboot=1" "quiet" "pti=off" "l1tf=off" "nospec_store_bypass_disable" 
"nospectre_v1" "nospectre_v2" "spec_store_bypass_disable"]; 
 boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" 
"sd_mod" "rtsx_pci_sdmmc" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-label/swap"; }];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

  # touchpad goes over i2c
  boot.blacklistedKernelModules = [ "psmouse" ];

#  config.opengl.extraPackages = with pkgs; [ # These are imported by ocl-icd
    #intel-ocl # intel cpu
#    beignet   # intel gpu
#  ];


  hardware.bumblebee.enable = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = false;
  };

  powerManagement.powertop.enable = true;
  services.undervolt = {
    enable = true;
    coreOffset = "-150";
    uncoreOffset = "-150";
    analogioOffset = "-150";
    temp = "97";
  };
}
