# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];
  boot.kernelParams = [ "i915.fastboot=1"
                        "quiet" "pti=off" "l1tf=off" "nospec_store_bypass_disable" 
"nospectre_v1" "nospectre_v2" "spec_store_bypass_disable"]; 

  boot.initrd.availableKernelModules = [ "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_acpi" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
      options = [ "data=writeback" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/boot";
      fsType = "vfat";
    };

   swapDevices = [{
     device = "/dev/disk/by-label/swap";
  }];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";

 hardware.opengl = {
   enable = true;
   extraPackages = with pkgs; [
      vaapiIntel
    ];
  };

}
